### ISSUE TITLE
Server error in some cases

### ISSUE THREAD

**Issue by lparsons** [Princeton-LSI-ResearchComputing/neuron-simulator#40]
### Problem

500 error on some parameter combinations

### Steps to reproduce

1. [Numbered](https://funsim.princeton.edu/neuronsimulator/?strain_type=wild-type&stim_type=realistic&stim_neu_id=AFDL&nt=1000&t_max=100.0&top_n=10&tau1=1.0&tau2=0.8)

### Current behavior

500 error.

### Expected behavior

A plot or error message if the values are invalid.

### Suggested Change

A guess at what might fix the issue.  *Pseudocode encouraged.*

### Comment

Any other relevant context or links to what you were working on when you
discovered the problem.

-----

### Assumptions

- List of assumptions made WRT the code
- E.g. We will assume input is correct (explaining why there is no validation)

### Requirements

- List of conditions to be met for the feature
- E.g. Every column/row must display a value, i.e. cannot be empty

### Limitations

- A list of things this work will not fix
- E.g. Getting edge case X to work requires too much effort and will not be
  fixed in this effort.

### Affected/Changed Components

- Files
- Environment variables
- External executables
- Database tables
- Cron job settings
- Etc.

#### GUI Change description

Describe changes the user will see.

#### Code Change Description *(Pseudocode optional)*

Describe code changes planned for the fix.

#### Tests

A test should be planned for each requirement (above), where possible.

**Comment by fkang-pu** [comment]
It's caused by three factors: 1) Francesco updated his code to version 0.1.9.4. including pickle files; 2) The code running on the server uses pickle files from version 0.1.9.1. 3) need to update code in utils.py in order to get correct list of neurons after Francesco fixed a bug in `get_neuron_ids` method. If working correctly, the above case shouldn't be on neuron pulldown list for wild-type. I will submit a Pull Request to address this issue later today.

**Comment by lparsons** [comment]
Nice detective work! I had thought I had updated the virtualenv on the server to use the latest (0.1.9.4) version of wormfunconn, but perhaps I forgot?

**Comment by fkang-pu** [comment]
It's not your fault. It's mainly due to the changes Francesco made and how he manages his code base.  Here are the main steps we need to do on our end:

1. always run "pip install requirement.txt" both locally and on the server ( install his code in `wormfunconn`  directory).
2. evaluate if pickle files are changed (in `atlas` directory). If yes, create a new local branch to update files in MEDIA_ROOT/atlas, and push to GitHub after testing.
3. evaluate if any code on our end (mainly `utils.py` and `forms.py`) needs to be updated based on changes he made. If yes, create a new local branch to update code, and then push to GitHub after testing.
4. redeploy the code to the server if necessary.

**Comment by lparsons** [comment]
Ah, I see. I had updated `wormfunconn` but not copied things over to `MEDIA_ROOT/atlas` directory. It would be nice to be able to use the pickle files that `wormfunconn` comes with. I think the "fix" for that would lie in Francesco's code, however.
